### PR TITLE
Feat deploy dd proposal

### PR DESCRIPTION
**Pull request by douglasduteil**
# Here comes my deployment solution boys

predeployment 15jan04 deploy

<br>
<br>

I'm merging it in one hour... Just to let you check
I will add some doc too.

---
## Usage

Basically the process is following what I described in #11

**gulp release**  will _bump_, _update the changelog_, and _push_ the sources under a commit version like `chore(release): srcX.Y.Z` with the tag `srcX.Y.Z` on it.

Tags `/^src\d+\.\d+\.\d+.*$/` will trigger **gulp publish** on the CI.

**gulp publish** will publish the built files and the pages with for the specified version.

<br>
<br>

**Notes** :
We might need to tweak the `main` key in the `bower.json` to fit the different case like :
- main sources in `master` branch are in `src/*/*`
- main sources in `dist` branch are in `*`

### CODE REVIEW

**Comment by mgcrea** [comment]
Why `srcX.Y.Z` vs `vX.Y.Z`?

**Comment by douglasduteil** [comment]
`vX.Y.Z` or `X.Y.Z` versions must be linked to the distributed sources (the dist result) so when you're grabbing the repo from the npm or bower you directly have the distribution version from the dist branch (repo without the tests, docs, and other Dev files). Like npm or bower get those tags by default.

The `srcX.Y.Z` tags will be on the master branch in sync with the `vX.Y.Z` so you can still grab the sources from there for the same version. And you're happily versioning you're sources.

**Comment by revolunet** [comment]
sounds perfect !
just wondering if the travis stuff is mandatory and if you found a solution for the travis-encrypt process ?

**Comment by douglasduteil** [comment]
> just wondering if the travis stuff is mandatory and if you found a solution for the travis-encrypt process ?

Yeah maybe. You will have to get the github token from the GitHub API an encode it in thee `.travis` with travis-encrypt as  `REPO` in the env. (Yes the name is not obvious and _have_ to change in the future)

**Pull request merged**
